version: '3.9'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./static:/app/static
    depends_on:
      - nginx

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html/static
    depends_on:
      - app